.PHONY: clean All

All:
	@echo "----------Building project:[ pacman - Debug ]----------"
	@cd "pacman" && "$(MAKE)" -f  "pacman.mk" && "$(MAKE)" -f  "pacman.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ pacman - Debug ]----------"
	@cd "pacman" && "$(MAKE)" -f  "pacman.mk" clean
